# Generated by Django 4.2.7 on 2023-11-11 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_name', models.CharField(max_length=100)),
                ('GSTIN_num', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('house', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.CharField(max_length=100)),
                ('veg', models.BooleanField()),
                ('name_of_dish', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count_per_day', models.IntegerField()),
                ('dish_image', models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='dishImages/')),
                ('rest_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant')),
            ],
            options={
                'verbose_name': 'dish',
                'ordering': ('rest_id',),
            },
        ),
        migrations.CreateModel(
            name='Delivery_Agent',
            fields=[
                ('rider_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('lisence_num', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('area_of_work', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'driver',
                'ordering': ('area_of_work',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('cust_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Address_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'verbose_name': 'address',
                'ordering': ('cust_id__customer_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_gt_start_time'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('user', 'GSTIN_num')},
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('rest_id', 'dish_id'), name='unique_menu_item'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('dish_id', 'rest_id')},
        ),
        migrations.AddConstraint(
            model_name='delivery_agent',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='rider must be an adult'),
        ),
        migrations.AlterUniqueTogether(
            name='delivery_agent',
            unique_together={('user', 'lisence_num')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('user', 'cust_id')},
        ),
    ]
