# Generated by Django 4.2.7 on 2023-11-14 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu_description_restaurant_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='rest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
    ]
