# Generated by Django 4.2.7 on 2023-11-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_address_book_address_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cust_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu')),
            ],
            options={
                'verbose_name': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_of_delivery', models.CharField(max_length=100)),
                ('address_of_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.address_book')),
                ('cart_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.cart')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant')),
                ('rider_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.delivery_agent')),
            ],
            options={
                'verbose_name': 'order',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review', models.TextField(max_length=255)),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant')),
            ],
            options={
                'verbose_name': 'rating and reviews',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('payment_time', models.TimeField()),
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'payment',
            },
        ),
    ]
