# Generated by Django 4.2.7 on 2023-11-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_address_book_address_type_and_more'),
        ('order', '0002_alter_cart_cust_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cust_id',
        ),
        migrations.AddField(
            model_name='order',
            name='cust_id',
            field=models.ManyToManyField(to='main.customer'),
        ),
    ]
