# Generated by Django 4.2.7 on 2023-11-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_address_book_address_type_and_more'),
        ('order', '0003_remove_order_cust_id_order_cust_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cust_id',
        ),
        migrations.AddField(
            model_name='order',
            name='cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer'),
        ),
    ]
