# Generated by Django 4.2.7 on 2023-11-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_cust_id_order_cust_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_item',
            field=models.ManyToManyField(to='order.cart'),
        ),
    ]
