# Generated by Django 4.2.7 on 2023-11-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_cart_item_order_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='IN_CART', max_length=100),
        ),
    ]
